#! /bin/bash

### BEGIN INIT INFO
# Provides:          rest-API
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start pkz019_SIC REST API at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

command_opts="/opt/pkz019_SIC_Api_Rest/server.js"

#export PATH=$PATH:/usr/local/bin:/usr/bin/node
export PATH=$PATH:/usr/bin/node
export NODE_PATH=$NODE_PATH:/opt/pkz019_SIC_Api_Rest/node_modules

case "$1" in
  start)
  exec forever --sourceDir=/opt/pkz019_SIC_Api_Rest -p /opt/pkz019_SIC_Api_Rest start server.js
  ;;
stop)
  exec forever stop --sourceDir=/opt/pkz019_SIC_Api_Rest server.js
  ;;
*)
  echo "Usage: /etc/init.d/pkz019_SIC_Api_Rest {start|stop}"
  exit 1
  ;;
esac

exit 0

